# Exported from:        http://MBP-Marin:5516/
# Release version:      24.1.0
# Date created:         Wed Oct 09 16:14:03 CEST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_AWS SecretsManager create secret.yaml
  - Workflow_AWS SecretsManager delete secret.yaml
  - Workflow_AWS SecretsManager update secret.yaml
  - Workflow_Azure KeyVault create secret.yaml
  - Workflow_Azure KeyVault delete secret.yaml
  - Workflow_Azure KeyVault update secret.yaml
