# Exported from:        http://MBP-Marin:5516/
# Release version:      24.1.0
# Date created:         Wed Oct 09 16:14:03 CEST 2024

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: Templates
  home: Digital.ai - Official/Templates
spec:
- directory: "."
  teams:
  - name: Folder Owner
  - name: Template Owner
  - name: Viewer
    roles:
    - Authenticated Users
    permissions:
    - folder#view
    - release#start
    - release#view
    - template#create_release
    - template#view
  - name: Release Admin
