# Exported from:        http://MBP-Marin:5516/
# Release version:      24.1.0
# Date created:         Wed Oct 09 16:14:02 CEST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
  - Workflow_CheckmarxOne scan Git repository.yaml
